/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.audio;

public class AC3Decoder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AC3Decoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AC3Decoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        audiodecoderJNI.delete_AC3Decoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setChannelLayout(int value) {
    audiodecoderJNI.AC3Decoder_ChannelLayout_set(swigCPtr, this, value);
  }

  public int getChannelLayout() {
    return audiodecoderJNI.AC3Decoder_ChannelLayout_get(swigCPtr, this);
  }

  public AC3Decoder(int flags) {
    this(audiodecoderJNI.new_AC3Decoder(flags), true);
  }

  public int decodeDirect(java.nio.ByteBuffer pchInput, int length) {
    return audiodecoderJNI.AC3Decoder_decodeDirect(swigCPtr, this, pchInput, length);
  }

  public int decode(byte[] BYTE, int offset, int length) {
    return audiodecoderJNI.AC3Decoder_decode(swigCPtr, this, BYTE, offset, length);
  }

  public boolean readDirect(java.nio.ByteBuffer pchInput, int length) {
    return audiodecoderJNI.AC3Decoder_readDirect(swigCPtr, this, pchInput, length);
  }

  public boolean read(byte[] BYTE, int offset, int length) {
    return audiodecoderJNI.AC3Decoder_read(swigCPtr, this, BYTE, offset, length);
  }

  public int getChannels() {
    return audiodecoderJNI.AC3Decoder_getChannels(swigCPtr, this);
  }

  public int getSampleRate() {
    return audiodecoderJNI.AC3Decoder_getSampleRate(swigCPtr, this);
  }

  public int getBitRate() {
    return audiodecoderJNI.AC3Decoder_getBitRate(swigCPtr, this);
  }

  public final static int LayoutStereo = audiodecoderJNI.AC3Decoder_LayoutStereo_get();
  public final static int LayoutDolby = audiodecoderJNI.AC3Decoder_LayoutDolby_get();
  public final static int Layout50 = audiodecoderJNI.AC3Decoder_Layout50_get();
  public final static int Layout51 = audiodecoderJNI.AC3Decoder_Layout51_get();

}
