/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.audio;

public class audiodecoderJNI {
  public final static native int AC3Decoder_LayoutStereo_get();
  public final static native int AC3Decoder_LayoutDolby_get();
  public final static native int AC3Decoder_Layout50_get();
  public final static native int AC3Decoder_Layout51_get();
  public final static native void AC3Decoder_ChannelLayout_set(long jarg1, AC3Decoder jarg1_, int jarg2);
  public final static native int AC3Decoder_ChannelLayout_get(long jarg1, AC3Decoder jarg1_);
  public final static native long new_AC3Decoder(int jarg1);
  public final static native void delete_AC3Decoder(long jarg1);
  public final static native void AC3Decoder_setDecodeBuffer(long jarg1, AC3Decoder jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native int AC3Decoder_decode(long jarg1, AC3Decoder jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native int AC3Decoder_getChannels(long jarg1, AC3Decoder jarg1_);
  public final static native int AC3Decoder_getSampleRate(long jarg1, AC3Decoder jarg1_);
  public final static native int AC3Decoder_getBitRate(long jarg1, AC3Decoder jarg1_);
  public final static native long new_MpegAudioDecoder();
  public final static native void delete_MpegAudioDecoder(long jarg1);
  public final static native void MpegAudioDecoder_setDecodeBuffer(long jarg1, MpegAudioDecoder jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native int MpegAudioDecoder_decode(long jarg1, MpegAudioDecoder jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native int MpegAudioDecoder_getChannels(long jarg1, MpegAudioDecoder jarg1_);
  public final static native int MpegAudioDecoder_getSampleRate(long jarg1, MpegAudioDecoder jarg1_);


static {
	try {
		System.loadLibrary("a52");
		System.loadLibrary("mad");
		System.loadLibrary("audiodecoder");
	}
	catch (UnsatisfiedLinkError e) {
	}
}

}
