/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.ac3;

public class ac3decoderJNI {
  public final static native void SyncInfo_frameSizeInBytes_set(long jarg1, SyncInfo jarg1_, int jarg2);
  public final static native int SyncInfo_frameSizeInBytes_get(long jarg1, SyncInfo jarg1_);
  public final static native void SyncInfo_flags_set(long jarg1, SyncInfo jarg1_, int jarg2);
  public final static native int SyncInfo_flags_get(long jarg1, SyncInfo jarg1_);
  public final static native void SyncInfo_sampleRate_set(long jarg1, SyncInfo jarg1_, int jarg2);
  public final static native int SyncInfo_sampleRate_get(long jarg1, SyncInfo jarg1_);
  public final static native void SyncInfo_bitRate_set(long jarg1, SyncInfo jarg1_, int jarg2);
  public final static native int SyncInfo_bitRate_get(long jarg1, SyncInfo jarg1_);
  public final static native long new_SyncInfo();
  public final static native void delete_SyncInfo(long jarg1);
  public final static native int Decoder_layoutStereo_get();
  public final static native int Decoder_layoutDolby_get();
  public final static native int Decoder_layout50_get();
  public final static native int Decoder_layout51_get();
  public final static native void Decoder_channelLayout_set(long jarg1, Decoder jarg1_, int jarg2);
  public final static native int Decoder_channelLayout_get(long jarg1, Decoder jarg1_);
  public final static native long new_Decoder__SWIG_0(int jarg1);
  public final static native long new_Decoder__SWIG_1();
  public final static native void delete_Decoder(long jarg1);
  public final static native long Decoder_getSyncInfo(long jarg1, Decoder jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native boolean Decoder_decode(long jarg1, Decoder jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native int Decoder_getOutput(long jarg1, Decoder jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native int Decoder_getChannels(long jarg1, Decoder jarg1_);
  public final static native int Decoder_getSampleRate(long jarg1, Decoder jarg1_);
  public final static native int Decoder_getFlags(long jarg1, Decoder jarg1_);
  public final static native int Decoder_getOutputBufferSize(long jarg1, Decoder jarg1_);


static {
	try {
		System.loadLibrary("a52");
		System.loadLibrary("ac3decoder");
	}
	catch (UnsatisfiedLinkError e) {
	}
}

}
