/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.ac3;

public class SyncInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SyncInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SyncInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ac3decoderJNI.delete_SyncInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrameSizeInBytes(int value) {
    ac3decoderJNI.SyncInfo_frameSizeInBytes_set(swigCPtr, this, value);
  }

  public int getFrameSizeInBytes() {
    return ac3decoderJNI.SyncInfo_frameSizeInBytes_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    ac3decoderJNI.SyncInfo_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return ac3decoderJNI.SyncInfo_flags_get(swigCPtr, this);
  }

  public void setSampleRate(int value) {
    ac3decoderJNI.SyncInfo_sampleRate_set(swigCPtr, this, value);
  }

  public int getSampleRate() {
    return ac3decoderJNI.SyncInfo_sampleRate_get(swigCPtr, this);
  }

  public void setBitRate(int value) {
    ac3decoderJNI.SyncInfo_bitRate_set(swigCPtr, this, value);
  }

  public int getBitRate() {
    return ac3decoderJNI.SyncInfo_bitRate_get(swigCPtr, this);
  }

  public SyncInfo() {
    this(ac3decoderJNI.new_SyncInfo(), true);
  }

}
