/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robotv.msgexchange;

public class SessionListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SessionListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SessionListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniwrapJNI.delete_SessionListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    jniwrapJNI.SessionListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    jniwrapJNI.SessionListener_change_ownership(this, swigCPtr, true);
  }

  public void onNotification(Packet p) {
    jniwrapJNI.SessionListener_onNotification(swigCPtr, this, Packet.getCPtr(p), p);
  }

  public void onDisconnect() {
    jniwrapJNI.SessionListener_onDisconnect(swigCPtr, this);
  }

  public SessionListener() {
    this(jniwrapJNI.new_SessionListener(), true);
    jniwrapJNI.SessionListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
