/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.jniwrap;

public class Connection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Connection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Connection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniwrapJNI.delete_Connection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Connection() {
    this(jniwrapJNI.new_Connection(), true);
  }

  public boolean open(String hostname, int port) {
    return jniwrapJNI.Connection_open(swigCPtr, this, hostname, port);
  }

  public void abort() {
    jniwrapJNI.Connection_abort(swigCPtr, this);
  }

  public boolean close() {
    return jniwrapJNI.Connection_close(swigCPtr, this);
  }

  public boolean isOpen() {
    return jniwrapJNI.Connection_isOpen(swigCPtr, this);
  }

  public boolean isAborting() {
    return jniwrapJNI.Connection_isAborting(swigCPtr, this);
  }

  public boolean sendRequest(Packet request) {
    return jniwrapJNI.Connection_sendRequest(swigCPtr, this, Packet.getCPtr(request), request);
  }

  public Packet readResponse() {
    long cPtr = jniwrapJNI.Connection_readResponse__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Packet(cPtr, false);
  }

  public boolean readResponse(Packet p) {
    return jniwrapJNI.Connection_readResponse__SWIG_1(swigCPtr, this, Packet.getCPtr(p), p);
  }

  public Packet transmitMessage(Packet message) {
    long cPtr = jniwrapJNI.Connection_transmitMessage__SWIG_0(swigCPtr, this, Packet.getCPtr(message), message);
    return (cPtr == 0) ? null : new Packet(cPtr, true);
  }

  public boolean transmitMessage(Packet request, Packet response) {
    return jniwrapJNI.Connection_transmitMessage__SWIG_1(swigCPtr, this, Packet.getCPtr(request), request, Packet.getCPtr(response), response);
  }

  public void setTimeout(int timeout_ms) {
    jniwrapJNI.Connection_setTimeout(swigCPtr, this, timeout_ms);
  }

  public String getHostname() {
    return jniwrapJNI.Connection_getHostname(swigCPtr, this);
  }

  public void setPriority(int priority) {
    jniwrapJNI.Connection_setPriority(swigCPtr, this, priority);
  }

  public int getPriority() {
    return jniwrapJNI.Connection_getPriority(swigCPtr, this);
  }

}
