/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.jniwrap;

public class MpegAudioDecoder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MpegAudioDecoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MpegAudioDecoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniwrapJNI.delete_MpegAudioDecoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MpegAudioDecoder() {
    this(jniwrapJNI.new_MpegAudioDecoder(), true);
  }

  public int decode(Packet p, int src_length, byte[] BYTE, int offset, int dst_length) {
    return jniwrapJNI.MpegAudioDecoder_decode(swigCPtr, this, Packet.getCPtr(p), p, src_length, BYTE, offset, dst_length);
  }

  public int getChannels() {
    return jniwrapJNI.MpegAudioDecoder_getChannels(swigCPtr, this);
  }

  public int getSampleRate() {
    return jniwrapJNI.MpegAudioDecoder_getSampleRate(swigCPtr, this);
  }

}
