/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.msgexchange;

public class Ac3Decoder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Ac3Decoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Ac3Decoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        msgexchangeJNI.delete_Ac3Decoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setChannelLayout(int value) {
    msgexchangeJNI.Ac3Decoder_channelLayout_set(swigCPtr, this, value);
  }

  public int getChannelLayout() {
    return msgexchangeJNI.Ac3Decoder_channelLayout_get(swigCPtr, this);
  }

  public Ac3Decoder(int flags) {
    this(msgexchangeJNI.new_Ac3Decoder(flags), true);
  }

  public int decode(Packet p, int src_length, byte[] BYTE, int offset, int dst_length) {
    return msgexchangeJNI.Ac3Decoder_decode(swigCPtr, this, Packet.getCPtr(p), p, src_length, BYTE, offset, dst_length);
  }

  public int getChannels() {
    return msgexchangeJNI.Ac3Decoder_getChannels(swigCPtr, this);
  }

  public int getSampleRate() {
    return msgexchangeJNI.Ac3Decoder_getSampleRate(swigCPtr, this);
  }

  public int getBitRate() {
    return msgexchangeJNI.Ac3Decoder_getBitRate(swigCPtr, this);
  }

  public final static int layoutStereo = msgexchangeJNI.Ac3Decoder_layoutStereo_get();
  public final static int layoutDolby = msgexchangeJNI.Ac3Decoder_layoutDolby_get();
  public final static int layout50 = msgexchangeJNI.Ac3Decoder_layout50_get();
  public final static int layout51 = msgexchangeJNI.Ac3Decoder_layout51_get();

}
