/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.msgexchange;

public class Packet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Packet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Packet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        msgexchangeJNI.delete_Packet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Packet(int msgid, int type, long uid) {
    this(msgexchangeJNI.new_Packet__SWIG_0(msgid, type, uid), true);
  }

  public Packet(int msgid, int type) {
    this(msgexchangeJNI.new_Packet__SWIG_1(msgid, type), true);
  }

  public Packet(int msgid) {
    this(msgexchangeJNI.new_Packet__SWIG_2(msgid), true);
  }

  public Packet() {
    this(msgexchangeJNI.new_Packet__SWIG_3(), true);
  }

  public void createUid() {
    msgexchangeJNI.Packet_createUid(swigCPtr, this);
  }

  public boolean putString(String string) {
    return msgexchangeJNI.Packet_putString(swigCPtr, this, string);
  }

  public boolean putU8(short c) {
    return msgexchangeJNI.Packet_putU8(swigCPtr, this, c);
  }

  public boolean putU16(int us) {
    return msgexchangeJNI.Packet_putU16(swigCPtr, this, us);
  }

  public boolean putS16(short s) {
    return msgexchangeJNI.Packet_putS16(swigCPtr, this, s);
  }

  public boolean putU32(long ul) {
    return msgexchangeJNI.Packet_putU32(swigCPtr, this, ul);
  }

  public boolean putS32(int l) {
    return msgexchangeJNI.Packet_putS32(swigCPtr, this, l);
  }

  public boolean putU64(java.math.BigInteger ull) {
    return msgexchangeJNI.Packet_putU64(swigCPtr, this, ull);
  }

  public boolean putS64(long ll) {
    return msgexchangeJNI.Packet_putS64(swigCPtr, this, ll);
  }

  public void clear() {
    msgexchangeJNI.Packet_clear(swigCPtr, this);
  }

  public void rewind() {
    msgexchangeJNI.Packet_rewind(swigCPtr, this);
  }

  public String getString() {
    return msgexchangeJNI.Packet_getString(swigCPtr, this);
  }

  public short getU8() {
    return msgexchangeJNI.Packet_getU8(swigCPtr, this);
  }

  public int getU16() {
    return msgexchangeJNI.Packet_getU16(swigCPtr, this);
  }

  public short getS16() {
    return msgexchangeJNI.Packet_getS16(swigCPtr, this);
  }

  public long getU32() {
    return msgexchangeJNI.Packet_getU32(swigCPtr, this);
  }

  public int getS32() {
    return msgexchangeJNI.Packet_getS32(swigCPtr, this);
  }

  public java.math.BigInteger getU64() {
    return msgexchangeJNI.Packet_getU64(swigCPtr, this);
  }

  public long getS64() {
    return msgexchangeJNI.Packet_getS64(swigCPtr, this);
  }

  public void setClientID(int oid) {
    msgexchangeJNI.Packet_setClientID(swigCPtr, this, oid);
  }

  public int getClientID() {
    return msgexchangeJNI.Packet_getClientID(swigCPtr, this);
  }

  public boolean eop() {
    return msgexchangeJNI.Packet_eop(swigCPtr, this);
  }

  public void freeze() {
    msgexchangeJNI.Packet_freeze(swigCPtr, this);
  }

  public long getPacketLength() {
    return msgexchangeJNI.Packet_getPacketLength(swigCPtr, this);
  }

  public long getPayloadLength() {
    return msgexchangeJNI.Packet_getPayloadLength(swigCPtr, this);
  }

  public long getUID() {
    return msgexchangeJNI.Packet_getUID(swigCPtr, this);
  }

  public int getMsgID() {
    return msgexchangeJNI.Packet_getMsgID(swigCPtr, this);
  }

  public int getType() {
    return msgexchangeJNI.Packet_getType(swigCPtr, this);
  }

  public long getCheckSum() {
    return msgexchangeJNI.Packet_getCheckSum(swigCPtr, this);
  }

  public long getPayloadCheckSum() {
    return msgexchangeJNI.Packet_getPayloadCheckSum(swigCPtr, this);
  }

  public void disablePayloadCheckSum() {
    msgexchangeJNI.Packet_disablePayloadCheckSum(swigCPtr, this);
  }

  public int getProtocolVersion() {
    return msgexchangeJNI.Packet_getProtocolVersion(swigCPtr, this);
  }

  public void setProtocolVersion(int version) {
    msgexchangeJNI.Packet_setProtocolVersion(swigCPtr, this, version);
  }

  public void setMsgID(int msgid) {
    msgexchangeJNI.Packet_setMsgID(swigCPtr, this, msgid);
  }

  public void setType(int type) {
    msgexchangeJNI.Packet_setType(swigCPtr, this, type);
  }

  public boolean compress(int level) {
    return msgexchangeJNI.Packet_compress(swigCPtr, this, level);
  }

  public boolean isCompressed() {
    return msgexchangeJNI.Packet_isCompressed(swigCPtr, this);
  }

  public boolean uncompress() {
    return msgexchangeJNI.Packet_uncompress(swigCPtr, this);
  }

  public void print() {
    msgexchangeJNI.Packet_print(swigCPtr, this);
  }

  public void copy(Packet p) {
    msgexchangeJNI.Packet_copy(swigCPtr, this, Packet.getCPtr(p), p);
  }

  public void skipBuffer(int length) {
    msgexchangeJNI.Packet_skipBuffer(swigCPtr, this, length);
  }

  public void readBuffer(byte[] BYTE, int offset, int length) {
    msgexchangeJNI.Packet_readBuffer(swigCPtr, this, BYTE, offset, length);
  }

  public final static int headerLength = msgexchangeJNI.Packet_headerLength_get();
  public final static int checkSumPos = msgexchangeJNI.Packet_checkSumPos_get();
  public final static int uncompressedPayloadLengthPos = msgexchangeJNI.Packet_uncompressedPayloadLengthPos_get();
  public final static int payloadLengthPos = msgexchangeJNI.Packet_payloadLengthPos_get();
  public final static int payloadCheckSumPos = msgexchangeJNI.Packet_payloadCheckSumPos_get();
  public final static int protocolVersionPos = msgexchangeJNI.Packet_protocolVersionPos_get();
  public final static int clientIDPos = msgexchangeJNI.Packet_clientIDPos_get();
  public final static int typePos = msgexchangeJNI.Packet_typePos_get();
  public final static int msgIDPos = msgexchangeJNI.Packet_msgIDPos_get();
  public final static int uIDPos = msgexchangeJNI.Packet_uIDPos_get();
  public final static int syncPos = msgexchangeJNI.Packet_syncPos_get();

}
