/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.msgexchange;

public class Session extends SessionProxy {
  private transient long swigCPtr;

  protected Session(long cPtr, boolean cMemoryOwn) {
    super(msgexchangeJNI.Session_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Session obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        msgexchangeJNI.delete_Session(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Session() {
    this(msgexchangeJNI.new_Session(), true);
  }

  public void setCallback(SessionListener listener) {
    msgexchangeJNI.Session_setCallback(swigCPtr, this, SessionListener.getCPtr(listener), listener);
  }

}
