/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xvdr.msgexchange;

public class SessionProxy extends Connection {
  private long swigCPtr;

  protected SessionProxy(long cPtr, boolean cMemoryOwn) {
    super(msgexchangeJNI.SessionProxy_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SessionProxy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        msgexchangeJNI.delete_SessionProxy(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    msgexchangeJNI.SessionProxy_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    msgexchangeJNI.SessionProxy_change_ownership(this, swigCPtr, true);
  }

  public SessionProxy() {
    this(msgexchangeJNI.new_SessionProxy(), true);
    msgexchangeJNI.SessionProxy_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean open(String hostname, int port) {
    return msgexchangeJNI.SessionProxy_open(swigCPtr, this, hostname, port);
  }

  public boolean close() {
    return msgexchangeJNI.SessionProxy_close(swigCPtr, this);
  }

  public boolean terminate() {
    return msgexchangeJNI.SessionProxy_terminate(swigCPtr, this);
  }

  public Packet transmitMessage(Packet message) {
    long cPtr = (getClass() == SessionProxy.class) ? msgexchangeJNI.SessionProxy_transmitMessage__SWIG_0(swigCPtr, this, Packet.getCPtr(message), message) : msgexchangeJNI.SessionProxy_transmitMessageSwigExplicitSessionProxy__SWIG_0(swigCPtr, this, Packet.getCPtr(message), message);
    return (cPtr == 0) ? null : new Packet(cPtr, true);
  }

  public boolean transmitMessage(Packet request, Packet response) {
    return (getClass() == SessionProxy.class) ? msgexchangeJNI.SessionProxy_transmitMessage__SWIG_1(swigCPtr, this, Packet.getCPtr(request), request, Packet.getCPtr(response), response) : msgexchangeJNI.SessionProxy_transmitMessageSwigExplicitSessionProxy__SWIG_1(swigCPtr, this, Packet.getCPtr(request), request, Packet.getCPtr(response), response);
  }

  protected void onNotification(Packet notification) {
    if (getClass() == SessionProxy.class) msgexchangeJNI.SessionProxy_onNotification(swigCPtr, this, Packet.getCPtr(notification), notification); else msgexchangeJNI.SessionProxy_onNotificationSwigExplicitSessionProxy(swigCPtr, this, Packet.getCPtr(notification), notification);
  }

}
