name: build (debug)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle (debug)
      run: |
        export DEBUG_VERSION=`git describe`
        ./gradlew assembleDebug
        cp -f ./robotv-atv/build/outputs/apk/debug/robotv-debug.apk robotv-debug-${DEBUG_VERSION}.apk 
        ./gradlew bundleDebug
        cp -f ./robotv-atv/build/outputs/bundle/debug/robotv-debug.aab robotv-debug-${DEBUG_VERSION}.aab
    - name: Archive binaries (debug)
      uses: actions/upload-artifact@v2
      with:
        name: debug-binaries
        path: |
          robotv-debug-*.apk
          robotv-debug-*.aab
