name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle (release)
      env:
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      run: |
        ./scripts/release-apk.sh
        ./scripts/release-bundle.sh
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: Version ${{ github.event.release.tag_name }}
        draft: false
        prerelease: false
        body_path: distribution/whatsnew/whatsnew-en-US
    - name: Upload binaries
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: distribution/bin/robotv-${{ github.event.release.tag_name }}.apk
        asset_name: robotv-${{ github.event.release.tag_name }}.apk
        asset_content_type: application/vnd.android.package-archive
    - name: Publish Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: org.robotv.robotv
        releaseFiles: distribution/bin/robotv-${{ github.event.release.tag_name }}.aab
        track: beta
        whatsNewDirectory: distribution/whatsnew
